"""Tests for the content tells: the words, placeholders and chrome of a
generated site, as opposed to its colours and shapes.

Each tell is checked both ways, as in test_scan.py. The left-alone cases
matter more here, because copy is where a scanner is most tempted to cry
wolf: "seamless" in a sentence is a hint, not a verdict, so the scanner only
reports vocabulary once a file has a cluster of it.

Run with: python3 -m unittest discover tests
"""

import datetime
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "skills", "polish"))

import scan  # noqa: E402


def categories(line):
    return [category for category, _ in scan.scan_line(line)]


def file_findings(text, name="page.html"):
    with tempfile.TemporaryDirectory() as root:
        with open(os.path.join(root, name), "w") as f:
            f.write(text)
        return scan.scan(root)


class Placeholders(unittest.TestCase):
    def test_lorem_ipsum_is_found(self):
        self.assertIn("placeholder", categories("<p>Lorem ipsum dolor sit amet, consectetur.</p>"))

    def test_placeholder_names_and_companies_are_found(self):
        for text in ("<h1>Your Company</h1>", "<p>Company Name Here</p>", "<span>John Doe</span>", "<span>Jane Smith</span>"):
            self.assertIn("placeholder", categories(text), text)

    def test_reserved_example_addresses_are_found(self):
        for text in ('placeholder="you@example.com"', "<a>hello@yourcompany.com</a>", "Call +1 (555) 123-4567", "123 Main Street, Anytown"):
            self.assertIn("placeholder", categories(text), text)

    def test_bracketed_fill_ins_are_found(self):
        self.assertIn("placeholder", categories("<blockquote>[Insert testimonial here]</blockquote>"))
        self.assertIn("placeholder", categories("<p>— [Your Name]</p>"))

    def test_placeholder_image_services_are_found(self):
        for text in (
            '<img src="https://placehold.co/600x400">',
            '<img src="https://via.placeholder.com/150">',
            'src="/placeholder.svg?height=400&width=600"',
            '<img src="https://i.pravatar.cc/100">',
            'src="https://randomuser.me/api/portraits/women/1.jpg"',
            'src="https://ui-avatars.com/api/?name=Sarah"',
            'src="https://api.dicebear.com/7.x/avataaars/svg"',
        ):
            self.assertIn("placeholder", categories(text), text)

    def test_default_page_titles_are_found(self):
        for text in ("<title>Vite + React</title>", "<title>Create Next App</title>", "<title>Document</title>", 'content="Generated by create next app"'):
            self.assertIn("placeholder", categories(text), text)

    def test_a_stale_copyright_year_is_found(self):
        last_year = datetime.date.today().year - 1
        self.assertIn("placeholder", categories(f"<p>© {last_year} Acme Inc. All rights reserved.</p>"))
        self.assertIn("placeholder", categories(f"&copy; 2019-{last_year} Acme"))

    def test_this_years_copyright_is_left_alone(self):
        year = datetime.date.today().year
        self.assertEqual(categories(f"<p>© {year} Panic & Wonder</p>"), [])
        self.assertEqual(categories(f"© 2019–{year} Chris Neale"), [])

    def test_coming_soon_and_text_goes_here_are_found(self):
        self.assertIn("placeholder", categories("<p>Coming soon</p>"))
        self.assertIn("placeholder", categories("<p>Description goes here</p>"))

    def test_a_real_name_and_address_are_left_alone(self):
        self.assertEqual(categories("<p>Chris Neale, 14 Vine Street, Bristol</p>"), [])
        self.assertEqual(categories("<a>chris@usablehq.com</a>"), [])


class BuilderBadges(unittest.TestCase):
    def test_builder_badges_are_found(self):
        for text in ("<a>Edit with Lovable</a>", "Made with Lovable", "Built with v0", "Made in Framer", 'src="https://cdn.gpteng.co/gptengineer.js"'):
            self.assertIn("badge", categories(text), text)

    def test_default_hosting_domains_are_found(self):
        for text in ("https://my-app.lovable.app", "https://coolsite.vercel.app/about", "https://x.bolt.host"):
            self.assertIn("badge", categories(text), text)

    def test_a_custom_domain_is_left_alone(self):
        self.assertEqual(categories('<a href="https://panicandwonder.com">'), [])


class DeadLinks(unittest.TestCase):
    def test_dead_hrefs_are_found(self):
        for text in ('<a href="#">About</a>', "<a href='javascript:void(0)'>", 'href="https://twitter.com"', 'href="https://linkedin.com/"'):
            self.assertIn("link", categories(text), text)

    def test_anchor_and_real_links_are_left_alone(self):
        for text in ('<a href="#features">', '<a href="/about">', 'href="https://twitter.com/onion2k"'):
            self.assertEqual(categories(text), [], text)


class Scaffolding(unittest.TestCase):
    def test_section_comments_are_found(self):
        for text in ("<!-- Hero Section -->", "{/* Features Section */}", "{/* Testimonials */}", "<!-- CTA -->"):
            self.assertIn("scaffold", categories(text), text)

    def test_todo_replace_with_real_data_is_found(self):
        self.assertIn("scaffold", categories("// TODO: replace with real data"))
        self.assertIn("scaffold", categories("{/* TODO: add real testimonials */}"))

    def test_an_ordinary_comment_is_left_alone(self):
        self.assertEqual(categories("<!-- The band between two eras. -->"), [])
        self.assertEqual(categories("// TODO: handle the leap-year case"), [])


class Testimonials(unittest.TestCase):
    def test_the_models_favourite_names_are_found(self):
        for name in ("Sarah Chen", "Marcus Chen", "Elena Vasquez", "Elara Voss", "Aris Thorne", "Amara Okafor"):
            self.assertIn("testimonial", categories(f"<cite>{name}</cite>"), name)

    def test_a_first_name_and_initial_is_found(self):
        self.assertIn("testimonial", categories("<cite>Sarah M.</cite>"))
        self.assertIn("testimonial", categories('name: "Michael R.",'))

    def test_stock_praise_is_found(self):
        for text in ("This product changed my life!", "Absolutely revolutionary!", "A game-changer for our team.", "I can't imagine working without it."):
            self.assertIn("testimonial", categories(f"<p>{text}</p>"), text)

    def test_generic_titles_at_generic_companies_are_found(self):
        self.assertIn("testimonial", categories("<span>CEO, TechCorp</span>"))
        self.assertIn("testimonial", categories("<span>Marketing Director at Startup Inc.</span>"))

    def test_a_real_quote_with_a_full_name_is_left_alone(self):
        self.assertEqual(categories("<p>It cut our invoicing from four days to six hours.</p>"), [])
        self.assertEqual(categories("<cite>Priya Raman, Head of Finance, Bramble</cite>"), [])

    def test_a_sentence_ending_in_a_capital_letter_is_not_an_initial(self):
        self.assertEqual(categories("<p>The score was Everton 2, Leeds 1. A draw.</p>"), [])

    def test_an_initial_followed_by_a_word_is_left_alone(self):
        self.assertEqual(categories("<p>I met Jane K. yesterday at the fair.</p>"), [])


class Statistics(unittest.TestCase):
    def test_round_number_customer_counts_are_found(self):
        for text in ("10,000+ happy customers", "500+ companies", "Join 1M+ users", "Trusted by 2,000+ teams"):
            self.assertIn("stat", categories(text), text)

    def test_uptime_ratings_and_multipliers_are_found(self):
        for text in ("99.9% uptime", "Rated 4.9/5", "24/7 support", "10x faster"):
            self.assertIn("stat", categories(text), text)

    def test_count_up_libraries_are_found(self):
        self.assertIn("stat", categories("import CountUp from 'react-countup'"))
        self.assertIn("stat", categories("const value = useCountUp({ end: 10000 })"))

    def test_a_sourced_or_exact_number_is_left_alone(self):
        self.assertEqual(categories("<p>386 events, 430 BC to 2026</p>"), [])
        self.assertEqual(categories("<p>1,204 customers as of March, per Stripe</p>"), [])


class CallsToAction(unittest.TestCase):
    def test_generic_button_labels_are_found(self):
        for text in (
            "<button>Get Started</button>",
            '<a class="btn">Get Started Free →</a>',
            "<Button>Learn More</Button>",
            "<a>Start Your Journey</a>",
            "<a>Click Here</a>",
            'label: "Book a Demo",',
        ):
            self.assertIn("cta", categories(text), text)

    def test_an_arrow_welded_to_a_link_is_found(self):
        self.assertIn("cta", categories("<a>See pricing &rarr;</a>"))
        self.assertIn("cta", categories("<a>See pricing →</a>"))

    def test_a_specific_label_is_left_alone(self):
        self.assertEqual(categories("<button>Start my 14-day trial</button>"), [])
        self.assertEqual(categories("<a>Read the 2025 report</a>"), [])

    def test_getting_started_in_docs_prose_is_left_alone(self):
        self.assertEqual(categories("<h2>Getting started with the API</h2>"), [])


class StockHeadings(unittest.TestCase):
    def test_stock_section_headings_are_found(self):
        for text in (
            "<h2>Everything you need to succeed</h2>",
            "<h2>Powerful features</h2>",
            "<h2>Why choose us?</h2>",
            "<h2>What our customers say</h2>",
            "<h2>Simple, transparent pricing</h2>",
            "<h2>Frequently asked questions</h2>",
            "<h2>Ready to get started?</h2>",
            "<h2>How it works</h2>",
            "<p>Trusted by industry leaders</p>",
            "<span>Most Popular</span>",
        ):
            self.assertIn("stock", categories(text), text)

    def test_template_faq_questions_are_found(self):
        for text in ("Is there a free trial?", "Can I cancel anytime?", "Do you offer refunds?", "Is my data secure?"):
            self.assertIn("stock", categories(f"<summary>{text}</summary>"), text)

    def test_a_heading_with_something_in_it_is_left_alone(self):
        self.assertEqual(categories("<h2>Ships to 14 countries</h2>"), [])
        self.assertEqual(categories("<h2>Atomic · 1945–1970</h2>"), [])


class GeneratedCopy(unittest.TestCase):
    def test_time_based_openers_are_found(self):
        for text in ("In today's fast-paced world,", "In today's digital age", "In a world where data is king", "Now more than ever,"):
            self.assertIn("copy", categories(text), text)

    def test_the_negation_pivot_is_found(self):
        for text in ("It's not just a tool — it's a transformation.", "We're not a company, we're a movement.", "This is more than just software."):
            self.assertIn("copy", categories(text), text)

    def test_verb_cosplay_phrases_are_found(self):
        for text in ("Unlock the power of your data", "Harness the power of AI", "Empower your team", "Transform your workflow with AI-powered insights"):
            self.assertIn("copy", categories(text), text)

    def test_throat_clearing_and_hooks_are_found(self):
        for text in ("It's important to note that", "At its core, the app", "Picture this:", "Let's dive in.", "Here's the thing:", "Imagine a world where"):
            self.assertIn("copy", categories(text), text)

    def test_generic_why_us_claims_are_found(self):
        for text in ("We are passionate about what we do", "committed to excellence", "Your success is our priority", "customer-centric solutions"):
            self.assertIn("copy", categories(text), text)

    def test_chatbot_register_and_citation_markup_are_found(self):
        for text in ("Certainly! Here's a landing page", "Great question!", "I hope this helps", "citeturn0search0", "?utm_source=chatgpt.com", "oaicite"):
            self.assertIn("copy", categories(text), text)

    def test_the_risk_reducer_triplet_is_found(self):
        self.assertIn("copy", categories("No credit card required · Cancel anytime · 14-day free trial"))

    def test_plain_prose_is_left_alone(self):
        self.assertEqual(categories("<p>One new weapon changes what people mean by the end of the world.</p>"), [])
        self.assertEqual(categories("<p>The first nuclear test in July was followed by the bombing of two cities.</p>"), [])

    def test_transform_in_css_is_left_alone(self):
        self.assertEqual(categories("transform: translateY(-2px);"), [])


class BuzzwordClusters(unittest.TestCase):
    CLUSTER = (
        "<p>A seamless, robust platform to elevate your workflow.</p>\n"
        "<p>Leverage cutting-edge, innovative tools.</p>\n"
        "<p>Effortless and intuitive.</p>\n"
    )

    def test_a_cluster_of_buzzwords_in_one_file_is_one_finding(self):
        findings = [f for f in file_findings(self.CLUSTER) if f["category"] == "buzzword"]
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0]["match"], "buzzword cluster")
        self.assertEqual(findings[0]["line"], 1)
        self.assertIn("seamless", findings[0]["detail"])
        self.assertIn("cutting-edge", findings[0]["detail"])

    def test_the_count_is_of_distinct_words(self):
        text = "<p>Seamless. Seamless. Seamless. Seamless. Seamless.</p>\n"
        self.assertEqual([f for f in file_findings(text) if f["category"] == "buzzword"], [])

    def test_the_same_word_on_four_lines_is_still_one_word(self):
        text = "<p>Seamless.</p>\n<p>Seamless.</p>\n<p>Seamless.</p>\n<p>Seamless.</p>\n"
        self.assertEqual([f for f in file_findings(text) if f["category"] == "buzzword"], [])

    def test_a_few_buzzwords_are_not_a_cluster(self):
        text = "<p>A robust way to streamline your day.</p>\n<p>It is fast.</p>\n"
        self.assertEqual([f for f in file_findings(text) if f["category"] == "buzzword"], [])

    def test_buzzwords_alone_are_never_line_findings(self):
        self.assertEqual(categories("<p>A seamless, robust, innovative, cutting-edge platform.</p>"), [])

    def test_the_cluster_is_in_the_report_with_its_words(self):
        report = scan.report(file_findings(self.CLUSTER))
        self.assertIn("Buzzword cluster (1)", report)
        self.assertIn("buzzword cluster", report)
        self.assertIn("seamless", report)


class EmDashes(unittest.TestCase):
    def test_a_file_thick_with_em_dashes_is_one_finding(self):
        text = "".join(f"<p>Line {i} — and more — again.</p>\n" for i in range(4))
        findings = [f for f in file_findings(text) if f["category"] == "dash"]
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0]["match"], "em dash density")
        self.assertIn("8", findings[0]["detail"])

    def test_a_few_em_dashes_are_left_alone(self):
        text = "<p>One — two.</p>\n<p>Three — four.</p>\n"
        self.assertEqual([f for f in file_findings(text) if f["category"] == "dash"], [])

    def test_an_em_dash_in_a_button_or_heading_is_a_finding_on_its_own(self):
        self.assertIn("dash", categories("<button>Start free — no card needed</button>"))
        self.assertIn("dash", categories("<h1>Plan — build — ship</h1>"))
        self.assertEqual(categories("<p>Plan — build — ship</p>"), [])


class Emoji(unittest.TestCase):
    def test_icon_emoji_in_markup_are_found(self):
        for text in ("<li>✨ AI-powered</li>", "<span>🚀</span>", "<h3>⚡ Lightning fast</h3>", "<div>🔒 Secure</div>", "<p>You're all set! 🎉</p>"):
            self.assertIn("emoji", categories(text), text)

    def test_emoji_in_a_css_file_or_a_flag_are_left_alone(self):
        self.assertEqual(categories("<span>🇬🇧 English</span>"), [])
        self.assertEqual(categories("/* ⚠ */ a { color: red; }"), [])

    def test_emoji_inside_a_comment_is_left_alone(self):
        self.assertEqual(categories("/* 🚀 ship it */ a { color: red; }"), [])
        self.assertEqual(categories("<!-- ✨ sparkle here -->"), [])


class AltText(unittest.TestCase):
    def test_generic_alt_text_is_found(self):
        for text in ('<img alt="hero image">', '<img alt="image">', '<img alt="placeholder">', '<img alt="feature icon">', '<img alt="image description">'):
            self.assertIn("alt", categories(text), text)

    def test_descriptive_and_empty_alt_are_left_alone(self):
        self.assertEqual(categories('<img alt="The Trinity test fireball, July 1945">'), [])
        self.assertEqual(categories('<img alt="">'), [])


class ScannedFiles(unittest.TestCase):
    def test_markdown_content_is_scanned_but_repo_docs_are_not(self):
        with tempfile.TemporaryDirectory() as root:
            os.makedirs(os.path.join(root, "src", "content"))
            with open(os.path.join(root, "src", "content", "about.md"), "w") as f:
                f.write("In today's fast-paced world, we deliver.\n")
            with open(os.path.join(root, "README.md"), "w") as f:
                f.write("In today's fast-paced world, we deliver.\n")
            with open(os.path.join(root, "CHANGELOG.md"), "w") as f:
                f.write("In today's fast-paced world, we deliver.\n")
            files = {f["file"] for f in scan.scan(root)}
        self.assertEqual(files, {os.path.join("src", "content", "about.md")})


if __name__ == "__main__":
    unittest.main()


class SlopFixture(unittest.TestCase):
    """A synthetic generated landing page, assembled from the tells the
    research describes, so that the whole catalogue gets a run end to end."""

    FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "slop")

    def findings(self):
        return scan.scan(self.FIXTURE)

    def test_it_hits_nearly_every_category(self):
        hit = {f["category"] for f in self.findings()}
        missing = set(scan.CATEGORIES) - hit
        # Beige, cream-and-terracotta and imagery are the light-mode tells; the fixture is dark.
        self.assertEqual(missing, {"beige", "tasteful", "imagery"})

    def test_the_whole_section_order_is_read_past_the_nav(self):
        order = [f for f in self.findings() if f["match"] == "stock section order"][0]
        self.assertEqual(order["detail"], "hero → logos → features → how it works → testimonials → pricing → faq → cta → footer")

    def test_a_glow_is_not_also_a_soft_shadow(self):
        mine = [f["category"] for f in self.findings() if "rgba(99, 102, 241" in f["match"]]
        self.assertIn("glow", mine)
        self.assertNotIn("shadow", mine)

    def test_one_phrase_is_one_finding(self):
        pivots = [f for f in self.findings() if f["category"] == "copy" and "not just" in f["match"]]
        self.assertEqual(len(pivots), 1)
        arrows = [f for f in self.findings() if f["category"] == "cta" and f["line"] == 18]
        self.assertEqual(len(arrows), 1)

    def test_no_detail_spans_lines(self):
        for finding in self.findings():
            self.assertNotIn("\n", finding.get("detail", ""), finding)
